apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-java-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-java-hello-world-deployment
  template:
    metadata:
      labels:
        app: spring-java-hello-world-deployment
    spec:
      containers:
        - name: spring-java-hello-world-pod
          image: spring-java-hello-world
          imagePullPolicy: Never # Forces minikube to pull from local Docker
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-java-hello-world-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32321
  selector:
    app: spring-java-hello-world-deployment
